version: 0.2

phases:
  install:
    commands:
      - npm install

  post_build:
    commands:
      - echo "Deploying..."

      # Get key from Parameter Store
      - aws ssm get-parameter --name "/deploy/key" --with-decryption --query Parameter.Value --output text > key.pem

      # Fix permission
      - chmod 400 key.pem

      # Copy files
      - scp -o StrictHostKeyChecking=no -i key.pem -r * ec2-user@3.6.36.97:~/app/

      # Run app
      - |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@3.6.36.97 << 'EOF'
        cd ~/app
        npm install
        nohup node app.js > output.log 2>&1 &
        EOF