version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Deploying to EC2"

      - echo "$EC2_KEY" > key.pem
      - chmod 400 key.pem

      - ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@13.233.215.215 "
          cd /home/ec2-user/node-app &&
          git pull origin main &&
          npm install &&
          pkill node || true &&
          nohup node app.js > output.log 2>&1 &
        "

artifacts:
  files:
    - '**/*'